config/routes.rb
Icookie::Application.routes.draw do
  root "static_pages#home"

  resources :users
  get "signup" => "users#new"

  resources :locations

  resource :session
  get "signin" => "sessions#new"

  # create friendlier URLs, like
  # "icookie.com/about" rather than "icookie.com/static_pages/about"
  StaticPagesController.action_methods.each do |action|
    get "/#{action}", :to => "static_pages##{action}", :as => "#{action}"
  end

end

app/models/location.rb
# CSV data for zip code and latitude/longitude
# sourced from http://greatdata.com/free-zip-code-database
class Location < ActiveRecord::Base

has_many :users

  def self.lat_lon_pairs
    active_zips = User.uniq.pluck(:zip)
    pairs       = []

    active_zips.each do |zip|
      spot  = self.find_by(:zip => zip)
      pair  = [spot.latitude, spot.longitude]
      pairs << pair
    end

    pairs
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location
  has_secure_password

  REPORT_OPTIONS = %w(full partial)

  validates :first_name, :last_name, :presence => true
  validates :email, :format => {
      :with    => /\A(\S+)@(.+)\.(\S+)\z/i,
      :message => "email address must conform to *@*.* format"
    },
    :uniqueness => { :case_sensitive => false }
  validates :zip, :length => {
      :is      => 5,
      :message => "zip code must be exactly 5 digits long"
    },
    :format => {
      :with    => /\d{5}/i,
      :message => "zip code must contain digits only" 
    }
  validates :report_detail, :inclusion => {:in => REPORT_OPTIONS}

  def self.authenticate(email, password)
    user = User.find_by(:email => email)
    user && user.authenticate(password)
  end

  def self.unique_zip_codes
    self.uniq.pluck(:zip)
  end

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def current_user?(user)
    current_user == user
  end
  helper_method :current_user?

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, :danger => "Please sign in first!"
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id]  = user.id
      flash[:success]    = "Welcome back #{user.first_name}!"
      redirect_to user
    else
      flash.now[:danger] = "Invalid Email/Password Combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :success => "You Have Successfully Signed Out!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render
  end

  def about
    render
  end

  def contact
    render
  end

  def success
    render
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, :only => [:show, :edit, :update, :destroy]
  before_action :require_correct_user, :only => [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to success_path, :success => "Signup Successful!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, :success => "Account Successfully Updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, :success => "Account Successfully Deleted!"
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :zip, 
                                 :password, :password_confirmation, :report_detail)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
    # green
    when :success
      "alert-success"
    # blue
    when :info
      "alert-info"
    # yellow
    when :warning
      "alert-warning"
    # red
    when :danger
      "alert-danger"
    else 
      flash_type.to_s
    end
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def profile_image_for(user)
    gravatar_url = "http://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(gravatar_url, :alt => "#{user.first_name} #{user.last_name}")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Cookie Report</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width-device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render :partial => "shared/header" %>
    <div class="container">
      <%= render :partial => "shared/flash_messages", :flash => flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <center><%= message %></center>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Cookie Report", root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if current_user %>
          <li><%= link_to current_user.first_name, current_user %></li>
          <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Sign Out", session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/about.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h2>Getting an accurate forecast blows.</h2>
    <p class="lead">Instead of the runaround, get the weather in your inbox daily.</p>
    <%= link_to "Sign Me Up!", signup_path, class: "btn btn-lg btn-success" %>
  </div>
</div>    

<div class="row marketing">
  <div class="col-lg-12">
    <h4>I'm Bill Turner, RC helicopter enthusiast.</h4>
    <h4>If you need details on the weather like me, you've probably asked:</h4>
    <ul>
      <li>Why am I screwing around in a different app?</li>
      <li>Why isn't the percent chance of rain listed?</li>
      <li>Why can't I see when the day will get hottest and coldest?</li>
      <li>Why isn't this specific to me?</li>
    </ul>

    <h4>The Cookie Report answers those questions with:</h4>
    <ul>
      <li>An email sent to you direct. You check your email first thing anyway you dirty dog ;).</li>
      <li>Rain details are explicit, including the hour that it's most likely to be worst.</li>
      <li>Daily max and min temps are timestamped.</li>
      <li>The forecast is specific to your zip code.</li>
    </ul>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="container">
  <div class="starter-template">
    <div class="container text-center">
      <h1>Have a question?</h1>

      <p class="lead">Holler at me <a href="mailto:brotoriousdev@gmail.com?subject=Whaddup">here.</a></p>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron center">
  <div class="container text-center">
    <h1>Today's Weather</h1>

    <p class="lead">Don't be a turkey. Get the forecast in your inbox daily.</p>

    <%= link_to "Sign Me Up!", signup_path, :class => "btn btn-lg btn-success" %>
  </div>
</div>

app/views/static_pages/success.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h2>You're in!</h2>
    <p class="lead">Forecasts start as soon as you confirm your email. Yahtzee!</p>
  </div>
</div>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :zip, :placeholder => "Must be 5 digits long" %>
  <%= f.email_field :email, :placeholder => "name@example.com" %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation, :label => "Confirm Your Password" %>
    <%= f.form_group :report_detail, :label => { :text => "Report Detail" } do %>
    <%= f.radio_button :report_detail, "full", :label => "The Whole Enchilada", :checked => true, :inline => true %>
    <%= f.radio_button :report_detail, "partial", :label => "Temperatures Only", :inline => true %>
  <% end %>
  <% if @user.new_record? %>
    <%= f.submit "Sign Up", :class => "btn btn-success" %>
  <% else %>
    <%= f.submit "Update Account", :class => "btn btn-success" %>
  <% end %>
<%= link_to "Cancel", root_path %>
<% end %>

app/views/users/edit.html.erb
<div>
  <h2>Editing Your Account Settings:</h2>
</div>
<%= render "form" %>

app/views/users/new.html.erb
<div>
  <h2>Almost there! Sign up and get the scoop:</h2>
</div>
<%= render "form" %>

app/views/users/show.html.erb
<div class="page-header">
  <%= profile_image_for(@user) %>
  <h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <ul class="list-group">
      <li class="list-group-item"><%= @user.email %></li>
      <li class="list-group-item"><%= @user.zip %></li>
      <% if @user.report_detail == "full" %>
        <li class="list-group-item">The Whole Enchilada</li>
      <% else %>
        <li class="list-group-item">Temperatures Only</li>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to "Edit Account", edit_user_path(@user), class: "btn btn-primary" %>
<%= link_to "Delete Account", @user, 
            :method => :delete,
            :data => { :confirm => "Are you sure you want to delete your account?" } %>